source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Koloda_Example', :exclusive => true do
  pod "Koloda", :path => "../"
  pod 'Alamofire', '~> 1.3'
end

target 'Koloda_Tests', :exclusive => true do
  pod "Koloda", :path => "../"

  
end
